# TODO: Add backend test and deploy
version: 2
jobs:
  build_frontend:
    working_directory: ~/nest
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "./frontend/package-lock.json" }}
      - run:
          name: Setup
          working_directory: ./frontend
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "./frontend/package-lock.json" }}
          paths:
            - ~/.node_modules
  test_frontend:
    docker:
      - image: circleci/node:10-browsers-legacy
    steps:
      - checkout
      - run:
          name: Setup
          working_directory: ./frontend
          command: npm ci
      - run:
          name: Test
          working_directory: ./frontend
          command: npm run test

workflows:
  version: 2
  build_and_test_frontend:
    jobs:
      - build_frontend
      - test_frontend:
          requires:
            - build_frontend
          filters:
            branches:
              only: master
